Improve 'html2markdown's web grabber code in an attempt to make it more robust, configurable and verbose ('dump/dumper' were replaced with 'grab/grabber', by the way): + New function 'grab_url_with' as the wrapper to web grabbers. + 'grab_url_with' can report errors if the grabber fails. + New command line option 'g' which explicitly selects a grabber and   _optionally_ specifies new options for the selected grabber.  Possible   use cases:     # Just use curl.     html2markdown -g 'curl'
    # Use wget by setting timeout to 10 seconds and limit retries to 2.
    html2markdown -g 'wget --timeout=10 --tries=2'
+ New command line option 'n' to avoid automatic web grabbing.

More refactorings:
+ Create a new function 'ensure_tempdir' and a global 'THIS_TEMPDIR' to 
  share the code for temporary file operations.  Modify all wrappers so as 
  to use this code.
+ Two small functions 'err' and 'errn' to print error messages.
+ New function 'usage' for usage message consistency.

Bug fix:
+ 'safein' was failing when it encountered "" arguments (this condition 
  does  hold when no argument given, that is, input is stdin).  Fix this 
  bug by checking arguments passed to 'safein'.

diff --git a/branches/wrappers/src/wrappers/html2markdown.in b/branches/wrappers/src/wrappers/html2markdown.in
--- a/branches/wrappers/src/wrappers/html2markdown.in
+++ b/branches/wrappers/src/wrappers/html2markdown.in
@@ -4,39 +4,117 @@
 
 REQUIRED=tidy
 SINGLE_FILE_INPUT=yes
-SYNOPSIS="[-o output_file] [-h] [input_file]"
 
 ### common.sh
 
-### getopts.sh
+grab_url_with () {
+    url="${1:?internal error: grab_url_with: url required}"
+
+    shift
+    cmdline="$@"
+
+    prog=
+    prog_opts=
+    if [ -n "$cmdline" ]; then
+	set -- $cmdline
+	prog=$1
+	shift
+	prog_opts="$@"
+    fi
+
+    if [ -z "$prog" ]; then
+	# Locate a sensible web grabber (note the order).
+	for p in wget lynx w3m curl links w3c; do
+		if pathfind $p; then
+		    prog=$p
+		    break
+		fi
+	done
+
+	[ -n "$prog" ] || {
+            errn "$THIS: Couldn't find a program to fetch the URL "
+	    err "(e.g. wget, w3m, lynx, w3c, or curl)."
+	    return 1
+	}
+    else
+	pathfind "$prog" || {
+	    err "$THIS: No such web grabber '$prog' found; aborting."
+	    return 1
+	}
+    fi
+
+    # Setup proper base options for known grabbers.
+    base_opts=
+    case "$prog" in
+    wget)  base_opts="-O-" ;;
+    lynx)  base_opts="-source" ;;
+    w3m)   base_opts="-dump_source" ;;
+    curl)  base_opts="" ;;
+    links) base_opts="-source" ;;
+    w3c)   base_opts="-n -get" ;;
+    *)     err "$THIS: unhandled web grabber '$prog'.  Hope it succeeds."
+    esac
+
+    set -- $base_opts $prog_opts
+
+    $prog "$@" "$url"; exitcode=$?
+
+    err "$THIS: '$prog $@ $url' invoked."
+    return $exitcode
+}
+
+SYNOPSIS="[-o output_file] [-g grabber_command] [-h] [-n] [input_file]..."
+
+grabber=
+outfile=
+nograb=
+while getopts g:o:nh opt; do
+    case $opt in
+    g) grabber="$OPTARG" ;;
+    o) outfile="$OPTARG" ;;
+    n) nograb=1 ;;
+    ?|h) usage "$SYNOPSIS"; exit 2 ;;
+    esac
+done
+
+shift $(($OPTIND - 1))
 
 ### postopts.sh
 
 if [ -n "$infile" ] && ! [ -f "$infile" ]; then
+    if [ -n "$nograb" ]; then
+	err "'$infile' not found; refusing to treat as URL."
+        exit 1
+    fi
+
     # Treat given argument as an URL.
-    echo >&2 "Attempting to fetch file from '$infile'..."
-    # Locate a sensible text based browser (note the order).
-    for p in wget lynx w3m curl links w3c; do
-        if pathfind $p; then
-            DUMPER=$p
-            break
+    err "Attempting to fetch file from '$infile'..."
+
+    # We need a temporary directory.
+    ensure_tempdir
+
+    grabber_out=$THIS_TEMPDIR/grabber.out
+    grabber_log=$THIS_TEMPDIR/grabber.log
+    if ! grab_url_with "$infile" "$grabber" 1>$grabber_out \
+                                            2>$grabber_log; then
+        errn "grab_url_with failed"
+        if [ -f $grabber_log ]; then
+            err " with the following error log."
+            err
+            cat >&2 $grabber_log
+        else
+            err .
         fi
-    done
-    # Setup proper options.
-    case "$DUMPER" in
-    wget)  OPT="-O-" ;;
-    lynx)  OPT="-source" ;;
-    w3m)   OPT="-dump_source" ;;
-    curl)  OPT="" ;;
-    links) OPT="-source" ;;
-    w3c)   OPT="-n -get" ;;
-    "")    printf "Needs a program to fetch the URL " >&2
-           printf "(e.g. wget, w3m, lynx, w3c, or curl).\n" >&2
-	   exit 1 ;;
-    esac
-    $DUMPER $OPT "$infile" | safein
-else
-    safein "$infile"
-fi |
-tidy -utf8 2>/dev/null |
+        exit 1
+    fi
+
+    # To be on the safe side detect bogus output.
+    infile=$grabber_out
+    if ! [ -f $infile ] || [ -z "$(tr -d [:space:] <$infile)" ]; then
+        err "Empty content returned from grabber."
+        exit 0
+    fi
+fi
+
+safein "$infile" | tidy -utf8 2>/dev/null |
 pandoc $PANDOC_OPTS -r html -w markdown -s | safeout "$outfile"
diff --git a/branches/wrappers/src/wrappers/markdown2pdf.in b/branches/wrappers/src/wrappers/markdown2pdf.in
--- a/branches/wrappers/src/wrappers/markdown2pdf.in
+++ b/branches/wrappers/src/wrappers/markdown2pdf.in
@@ -18,20 +18,19 @@ if [ -z "$outfile" ]; then
     fi
 fi
 
+set -e
+
 # We should use a filename without white spaces for pdflatex.
 TEXNAME=$THIS
 
-set -e
+ensure_tempdir
 
-TEMP=${TMPDIR-/tmp}/markdown2pdf.$$
-trap "exitcode=$?; rm -rf $TEMP; exit $exitcode" INT QUIT TERM EXIT
-mkdir -p $TEMP
-
-safein "$@" | pandoc $PANDOC_OPTS -w latex -s | safeout >$TEMP/$TEXNAME.tex && (
-    cd $TEMP
+safein "$@" |
+pandoc $PANDOC_OPTS -w latex -s | safeout >$THIS_TEMPDIR/$TEXNAME.tex && (
+    cd $THIS_TEMPDIR
     if ! pdflatex -interaction=batchmode $TEXNAME.tex >/dev/null 2>&1; then
-        echo >&2 "LaTeX errors:"
+        err "LaTeX errors:"
         sed -ne '/^!/,/^ *$/p' $TEXNAME.log >&2
         exit 1
     fi
-) && safeout $TEMP/$TEXNAME.pdf "$outfile"
+) && safeout $THIS_TEMPDIR/$TEXNAME.pdf "$outfile"
