Merged changes from trunk since r209.

diff --git a/branches/wrappers/Makefile b/branches/wrappers/Makefile
--- a/branches/wrappers/Makefile
+++ b/branches/wrappers/Makefile
@@ -19,11 +19,6 @@ CONFIGURE := configure
 NAME      := $(shell sed -ne 's/^[Nn]ame:[[:space:]]*//p' $(CABAL).in)
 VERSION   := $(shell sed -ne 's/^version[[:space:]]*=[[:space:]]*"\([^"]*\)"/\1/p' $(SRCDIR)/Main.hs)
 EXECSBASE := $(shell sed -ne 's/^[Ee]xecutable:[[:space:]]*//p' $(CABAL).in)
-# Add .exe extensions if we're running Windows/Cygwin.
-EXTENSION := $(shell uname | tr '[:upper:]' '[:lower:]' | sed -ne 's/^cygwin.*$$/\.exe/p')
-EXECS     := $(patsubst %,%$(EXTENSION),$(EXECSBASE))
-# First entry in Cabal's executable stanza is the main executable.
-MAIN      := $(firstword $(EXECS))
 
 #-------------------------------------------------------------------------------
 # Install targets
@@ -32,6 +27,12 @@ WRAPPERS  := web2markdown markdown2pdf
 SYMLINKS  := markdown2html markdown2latex markdown2s5 markdown2rst \
 			 markdown2rtf html2markdown latex2markdown rst2markdown
 PROGS     := $(EXECS) $(WRAPPERS) 
+# Add .exe extensions if we're running Windows/Cygwin.
+EXTENSION := $(shell uname | tr '[:upper:]' '[:lower:]' | \
+               sed -ne 's/^cygwin.*$$/\.exe/p')
+EXECS     := $(addsuffix $(EXTENSION),$(EXECSBASE))
+# First entry in Cabal's executable stanza is the main executable.
+MAIN      := $(firstword $(EXECS))
 DOCS      := README.html README BUGS TODO
 
 #-------------------------------------------------------------------------------
@@ -90,7 +91,6 @@ all: build-program
 
 .PHONY: templates
 templates: $(SRCDIR)/templates
-$(SRCDIR)/templates:
 	$(MAKE) -C $(SRCDIR)/templates
 
 .PHONY: symlinks
@@ -126,7 +126,7 @@ $(CABAL): cabalize $(CABAL).in $(SRCDIR)/Main.hs
 
 .PHONY: configure
 cleanup_files+=$(BUILDDIR) $(BUILDCONF) $(BUILDVARS)
-configure: $(BUILDCONF)
+configure: $(BUILDCONF) templates
 $(BUILDCONF): $(CABAL)
 	$(BUILDCMD) configure --prefix=$(PREFIX)
 	# Make configuration time settings persistent (definitely a hack).
@@ -134,7 +134,7 @@ $(BUILDCONF): $(CABAL)
 	@echo "DESTDIR?=$(DESTDIR)" >>$(BUILDVARS)
 
 .PHONY: build
-build: templates configure
+build: configure
 	$(BUILDCMD) build
 
 .PHONY: build-exec
@@ -336,6 +336,7 @@ web_dest:=web/pandoc
 make_page:=./$(MAIN) -s -B $(web_src)/header.html \
                         -A $(web_src)/footer.html \
 	                -H $(web_src)/css 
+win_main:=$(basename $(MAIN)).exe
 cleanup_files+=$(web_dest)
 website: $(web_dest)
 $(web_dest)/: $(MAIN) html $(tarball_name)
@@ -347,12 +348,17 @@ $(web_dest)/: $(MAIN) html $(tarball_name)
 		echo "*** Missing ../$(deb_main). ***"; \
 		exit 1; \
 	}
+	@[ -f $(win_main) ] || { \
+		echo "*** Missing $(win_main). ***"; \
+		exit 1; \
+	}
 	-rm -rf $(web_dest)
 	( \
 		mkdir $(web_dest); \
 		cp -r html $(web_dest)/doc; \
 		cp ../$(osx_dmg_name) $(web_dest)/; \
 		cp ../$(deb_main) $(web_dest)/; \
+		cp $(win_main) $(web_dest)/; \
 		cp $(tarball_name) $(web_dest)/; \
 		cp $(web_src)/*.css $(web_dest)/; \
 		sed -e 's#@PREFIX@#$(PREFIX)#g' $(osx_src)/Welcome | \
@@ -366,6 +372,8 @@ $(web_dest)/: $(MAIN) html $(tarball_name)
 		sed -e 's/@TARBALL_NAME@/$(tarball_name)/g' $(web_src)/index.txt | \
 			sed -e 's/@DEB_NAME@/$(deb_main)/g' | \
 			sed -e 's/@OSX_DMG_NAME@/$(osx_dmg_name)/g' | \
+			sed -e 's/@WINDOWS_EXE_NAME@/$(win_main)/g' | \
+			sed -e 's/@VERSION@/$(VERSION)/g' | \
 			$(make_page) > $(web_dest)/index.html; \
 	) || { rm -rf $(web_dest); exit 1; }
 
@@ -376,5 +384,6 @@ distclean: clean
 	fi
 
 clean:
+	make -C $(SRCDIR)/templates clean
 	-if [ -f $(BUILDCONF) ]; then $(BUILDCMD) clean; fi
 	-rm -rf $(cleanup_files)
